name: Update AWS Secrets Manager

on:
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update AWS Secrets Manager
        run: |
          aws secretsmanager describe-secret --secret-id YourSecret --region ap-south-1 > /dev/null 2>&1

          if [ $? -ne 0 ]; then
          aws secretsmanager create-secret --name YourSecret --secret-string '{"YourAPIKeyField":"'"${{ secrets.API_KEY }}"'"}' --region ap-south-1
          echo "Secret created successfully."
          else
          echo "Secret already exists. Skipping creation."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
