name: POC Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process_data:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run Python script
        run: python process_data.py
